spring.application.name=desafio-final-rpg

# Configuracao do banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/simulador
spring.datasource.username=postgres
spring.datasource.password=219693
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# URL base do rival -- troque pelo IP da maquina adversaria
rival.base.url=http://26.62.240.77:8080

# URLs derivadas da base -- nao precisa alterar
rival.chat.url=${rival.base.url}/chat/ouvir
rival.combate.url=${rival.base.url}/combate/apanhar

server.port=8080
server.address=0.0.0.0
